version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: root
    restart: unless-stopped
    ports:
      - 8080:8080
      - 5000:5000
    volume:
      - /var/jenkins_home:/var/jenkins_home

  network:
    jenkins:
