version: 3.8
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: root
    restart: unless-stopped
    ports:
      - 8080:8080
      - 5000:5000
    volume:
      - /usr/bin/docker:/usr/bin/docker
    network: jenkins

  network:
    jenkins:
      driver: bridge
